# Generated by Django 3.2.19 on 2023-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_ingredientinrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='IngredientInRecipe',
        ),
    ]
