# Generated by Django 3.2.19 on 2023-05-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_auto_20230526_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
