# Generated by Django 3.2.19 on 2023-05-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='guest', max_length=10, verbose_name='User Role'),
        ),
    ]
