# Generated by Django 3.2.19 on 2023-05-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['user', 'author'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
