# Generated by Django 3.2.19 on 2023-05-19 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230518_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Введите корректный Никнэйм', regex='^[\\w.@+-]+\\Z')], verbose_name='Никнэйм пользователя'),
        ),
    ]
