# Generated by Django 3.2.19 on 2023-05-19 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20230519_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите электронную почту пользователя', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Никнэйм', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Введите корректный Никнэйм', regex='^[\\w.@+-]+\\Z')], verbose_name='Никнэйм'),
        ),
    ]
