# Generated by Django 3.2.19 on 2023-05-25 07:03

import django.contrib.auth.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230522_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Введите имя пользователя', max_length=150, validators=[users.validators.check_username], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию пользователя', max_length=150, validators=[users.validators.check_name], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Никнэйм', max_length=150, unique=True, validators=[users.validators.check_username, django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='Никнэйм'),
        ),
    ]
